meetingapp/urls.py
from django.conf.urls import patterns, include, url
from data import views
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', views.index),
    (r'^create/$', views.create),
    (r'^signup/$', views.signup),
    (r'^login/$', views.login),
    (r'^logout/$', views.logout),
    (r'^home/$', views.home),
    (r'^profile/$', views.profile),
    (r'^contacts/$', views.contacts),
    (r'^meeting/.{15}$', views.meeting),
    (r'^verify/.{25}$', views.verify),
    (r'^vote/$', views.vote),
    (r'^invite/$', views.invite),
    (r'^settings/$', views.settings),
    (r'^addorganizer/$', views.addorganizer),
    (r'^attachorg/$', views.attachorg),
    (r'^managemembers/$', views.managemembers),
    (r'^orgs/.{22}$', views.orgpage),
    (r'^profile/.{21}$', views.profpage),
    (r'^setinterview/$', views.setinterview),
    (r'^setchat/$', views.setchat),
    (r'^setnormal/$', views.setnormal),
    (r'^intersub/$', views.intersub),
    (r'^chatonline/$', views.chatonline),
    (r'^chatbanlist/$', views.chatbanlist),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),

    # Examples:
    # url(r'^$', 'meetingapp.views.home', name='home'),
    # url(r'^meetingapp/', include('meetingapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

data/forms.py
from django import forms
from django.forms.fields import DateField, TimeField
from django.forms import extras
from custom_widgets import SelectTimeWidget
import datetime
import html5.forms.widgets as html5_widgets
from buildtimezones import fillTZInfo

STATUS=[('Public', 'Public'), ('Private', 'Private')]
TYPES=[('Normal', 'Normal Meeting'), ('Interview', 'Interview'), ('Chat', 'Interactive Chat')]
FI=[('Yes', 'Yes'), ('No', 'No')]
TITLES = [('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('None', 'None')]
# TIMEZONES=[('UTC/GMT-12:00', 'UTC/GMT-12:00'), ('UTC/GMT-11:00', 'UTC/GMT-11:00'),
# 			('UTC/GMT-10:00', 'UTC/GMT-10:00'), ('UTC/GMT-9:00', 'UTC/GMT-9:00'), ('PDT (UTC/GMT-8:00)', 'PDT (UTC/GMT-8:00)'),
# 			('MDT (UTC/GMT-7:00)', 'MDT (UTC/GMT-7:00)'), ('CDT (UTC/GMT-6:00)', 'CDT (UTC/GMT-6:00)'), 
# 			('EDT (UTC/GMT-5:00)', 'EDT (UTC/GMT-5:00)'), ('UTC/GMT-4:00', 'UTC/GMT-4:00'), ('UTC/GMT-3:00', 'UTC/GMT-3:00'), 
# 			('UTC/GMT-2:00', 'UTC/GMT-2:00'), ('UTC/GMT-1:00', 'UTC/GMT-1:00'), 
# 			('UTC/GMT','UTC/GMT'), 
# 			('UTC/GMT+1:00','UTC/GMT+1:00'), ('UTC/GMT+2:00','UTC/GMT+2:00'), ('EAT (UTC/GMT+3:00)', 'EAT (UTC/GMT+3:00)'),
# 			('UTC/GMT+4:00', 'UTC/GMT+4:00'), ('UTC/GMT+5:00', 'UTC/GMT+5:00'), ('UTC/GMT+6:00', 'UTC/GMT+6:00'),
# 			('UTC/GMT+7:00', 'UTC/GMT+7:00'), ('UTC/GMT+8:00', 'UTC/GMT+8:00'), ('UTC/GMT+9:00', 'UTC/GMT+9:00'),
# 			('UTC/GMT+10:00', 'UTC/GMT+10:00'), ('UTC/GMT+11:00', 'UTC/GMT+11:00'), ('UTC/GMT+12:00', 'UTC/GMT+12:00')]
valid_time_formats=['%I:%M%p']
TIMEZONES = fillTZInfo()

class UserForm(forms.Form):
	username = forms.CharField(required=False)
	first_name = forms.CharField()
	last_name = forms.CharField()
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
	retype = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
	phone = forms.CharField(required=False)

class ChatForm(forms.Form):
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
	agreed = forms.ChoiceField(choices=FI, widget=forms.RadioSelect())
	desc = forms.CharField()

class DTInterviewForm(forms.Form):
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
	agreed = forms.ChoiceField(choices=FI, widget=forms.RadioSelect())
	startdate = forms.DateField()
	starttime = forms.TimeField(widget=SelectTimeWidget(twelve_hr=True, use_seconds=False))
	enddate = forms.DateField()
	endtime = forms.TimeField(widget=SelectTimeWidget(twelve_hr=True, use_seconds=False))
	description = forms.CharField()

class InterviewForm(forms.Form):
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
	agreed = forms.ChoiceField(choices=FI, widget=forms.RadioSelect())
	desc = forms.CharField()

class ContactForm(forms.Form):
	title = forms.ChoiceField(choices=TITLES, widget=forms.Select(attrs={'style':'width: 70px !important;'}), required=False)
	first_name = forms.CharField(required=False)
	last_name = forms.CharField(required=False)
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
	wphone = forms.CharField(required=False)
	hphone = forms.CharField(required=False)
	address = forms.CharField(required=False)

class MeetingForm(forms.Form):
	title = forms.CharField()
	desc = forms.CharField(widget=forms.Textarea(attrs={'rows':'3', 'cols':'40','maxlength':250}), max_length=500)
	use_dt = forms.ChoiceField(choices=FI, widget=forms.RadioSelect())
	startdate = forms.DateField(required=False)
	starttime = forms.TimeField(widget=SelectTimeWidget(twelve_hr=True, use_seconds=False), required=False)
	enddate = forms.DateField(required=False)
	location = forms.CharField(required=False)
	endtime = forms.TimeField(widget=SelectTimeWidget(twelve_hr=True, use_seconds=False), required=False)
	timezone = forms.ChoiceField(choices=TIMEZONES, widget=forms.Select(attrs={'style':'height: 30px !important;'}))
	status = forms.ChoiceField(choices=STATUS, widget=forms.RadioSelect())
	interview = forms.ChoiceField(choices=TYPES, widget=forms.RadioSelect())
	image = forms.ImageField(required=False)

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

class OrganizationForm(forms.Form):
	name = forms.CharField()
	desc = forms.CharField(widget=forms.Textarea(attrs={'rows':'3', 'cols':'40','maxlength':250}))
	image = forms.ImageField(required=False)
	contact = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
	website = forms.CharField(required=False)

class OrgEmailForm(forms.Form):
	contact = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}), required=False)

class MeetingOrgForm(forms.Form):
	name = forms.CharField(required=False)
	desc = forms.CharField(widget=forms.Textarea(attrs={'rows':'3', 'cols':'40','maxlength':250}), required=False)
	image = forms.ImageField(required=False)
	contact = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}), required=False)
	website = forms.CharField(required=False)

class SettingsForm(forms.Form):
	title = forms.CharField(required=False)
	desc = forms.CharField(widget=forms.Textarea(attrs={'rows':'3', 'cols':'40','maxlength':250}), max_length=500, required=False)
	startdate = forms.DateField(required=False)
	starttime = forms.TimeField(widget=SelectTimeWidget(twelve_hr=True, use_none=True, use_seconds=False), required=False)
	enddate = forms.DateField(required=False)
	endtime = forms.TimeField(widget=SelectTimeWidget(twelve_hr=True, use_none=True, use_seconds=False), required=False)
	status = forms.ChoiceField(choices=STATUS, widget=forms.RadioSelect(), required=False)
	fi = forms.ChoiceField(choices=FI, widget=forms.RadioSelect(), required=False)

class ImgForm(forms.Form):
	image = forms.ImageField(required=False)

meetingapp/templates/addorganizer.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<form enctype="multipart/form-data" class="form-horizontal centered" style="display:inline-block;" method="post">
		{% csrf_token %}
		<div class="control-group">
			<div class="controls">
				<h3>Create New Organization</h3>
			</div>
		</div>
		<input type="hidden" name="submit_request" value="submit_request">
		<div class="control-group">
			<label class="control-label" for="inputEmail">Name</label>
			<div class="controls">
	            {{form.name}} {% if form.name.errors %}<text style="color: red; padding-left: 5px;">Required</text>{% endif %}
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="inputPassword">Description</label>
			<div class="controls">
				{{form.desc}} {% if form.desc.errors %}<text style="color: red; padding-left: 5px;">Required</text>{% endif %}
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="inputPassword">Contact Email</label>
			<div class="controls">
				{{form.contact}} {% if form.contact.errors %}<text style="color: red; padding-left: 5px;">Invalid Input</text>{% endif %}
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="inputws">Website</label>
			<div class="controls">
				{{form.website}}
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="inputPassword">Image</label>
			<div class="controls">
				{{form.image}} {% if form.image.errors %}<h5 style="color: red;">Image is too large.</h5>{% endif %}
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<button type="submit" class="btn btn-primary">Create Organization</button>
			</div>
		</div>
	</form>
</div>

{% endblock %}

meetingapp/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Vital Meeting &middot; Make Things Happen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load staticfiles %}

    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
    <link href="{% static "base.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "jquery/base/jquery-ui.css" %}" rel=`"stylesheet" type="text/css">
    <link href="{% static "jquery/base/jquery.ui.datepicker.css" %}" rel="stylesheet" type="text/css">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "datepicker/js/bootstrap-datepicker.js" %}"></script>
    
    <link href="{% static "datepicker/css/datepicker.css" %}" rel="stylesheet" type="text/css">

    <link href="{% static "flexslider/flexslider.css" %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static "vitalmeeting.css" %}" />

    <!--<script src="{% static "jquery/ui/jquery.ui.core.js" %}"></script>
    <script src="{% static "jquery/ui/jquery.ui.widget.js" %}"></script>

    <script src="{% static "jquery/ui/jquery.ui.datepicker.js" %}"></script>-->


</head>

<body style="padding: 0px;">
<div class="header" style="margin-bottom: 40px;">

  <div id="box1">
    {% if not user.is_authenticated %}
      <table>
      <tr class="header">
      <td class="column1"> <a href="/"> <img src="{% static "images/logo.gif" %}" width="258" height="46" alt="Vital Meeting"> </a> </td>
      <td class="column2"> <a id="column2" href=""> What is Vital <br /> Meeting? </a> </td>
      <td class="column3"> <a href=""> <span> See </span> </a> people <br /> making it happen </td>
      <td class="column4"> <a href="/create/"> <span> Start </span> </a> <br /> your meeting </td>
      <td class="column5"> <a href=""> help </a> </td>
      <td class="column6"> <a href="/signup/"> signup </a> </td>
      <td class="column7"> <a href="/login/"> login </a> </td>
      </tr>
      </table>
    {% else %}
    <table>
    <tr class="header">
    <td class="column1"> <a href="/"> <img src="{% static "images/logo.gif" %}" width="258" height="46" alt="Vital Meeting"> </a> </td>
    <td class="column3"> <a href=""> <span> See </span> </a> people <br /> making things happen </td>
    <td class="column4"> <a href="/contacts/"> <span> My Contacts </span> </a> </td>
    <td class="column4"> <a href="/home/"> <span> My Meetings </span> </a> </td>
    <td class="column5"> <a href=""> help </a> </td>
    <td class="column6"> <a href=""> {% if account.prof_pic != 'None' %}<img src="{{account.prof_pic.url}}" style="width: 50px; height: 50px;"> {% endif %}</a> </td>
    <td class="column7"> {{user.first_name}} {{user.last_name}}<br /> <a href="../logout/"> logout </a> </td>
    </tr>
    </table>
    {% endif %}
  </div> <!-- end of box1 -->

</div>
<div class="container">
  {% block content %}
      Content
  {% endblock %}
</div>

<!-- <div class="footer" style="margin-top: 50px;">
<p>
<ul>
<li> <a href=""> help </a>  </li>
<li> <a href=""> privacy </a>  </li>
<li> <a href=""> terms </a>  </li>
<li> <a href=""> contact </a>  </li>
<li> <a href=""> copyright &copy; 2013 VitalMeeting, Inc.  </a> </li>
</ul>
</p>
</div> -->

</body>

<script type='text/javascript'>
var _glc =_glc || []; _glc.push('all_ag9zfmNsaWNrZGVza2NoYXRyDgsSBXVzZXJzGJn89g4M');
var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' : 
'http://my.clickdesk.com/clickdesk-ui/browser/');
var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
var glcspt = document.createElement('script'); glcspt.type = 'text/javascript'; 
glcspt.async = true; glcspt.src = glcpath + 'livechat-new.js';
var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(glcspt, s);
</script>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42713435-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</html>

meetingapp/templates/home.html
<!DOCTYPE html>
<head>
<title> Vital Meeting - UserPage </title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "vitalmeeting.css" %}" />
</head>
<body>

<div id="box1">
<table>
<tr class="header">
<td class="column1"> <a href="/"> <img src="{% static "images/logo.gif" %}" width="258" height="46" alt="Vital Meeting"> </a> </td>
<td class="column3"> <a href=""> <span> See </span> </a> people <br /> making things happen </td>
<td class="column4"> <a href="/contacts/"> <span> My Contacts </span> </a> </td>
<td class="column4"> <a href="/home/"> <span> My Meetings </span> </a> </td>
<td class="column5"> <a href=""> help </a> </td>
<td class="column6"> <a href=""> {% if account.prof_pic != 'None' %}<img src="{{account.prof_pic.url}}" style="width: 50px; height: 50px;"> {% endif %}</a> </td>
<td class="column7"> {{user.first_name}} {{user.last_name}}<br /> <a href="../logout/"> logout </a> </td>
</tr>
</table>
</div> <!-- end of box1 -->

<div id="meetingnav">
<ul class="nav">
<li> <a href="" id="mymeetings">My Meetings</a> </li>
<li> <a href="../create/">Create A Meeting</a> </li>
<li> <a href="../addorganizer/">Create An Organization</a> </li>
<li> <a href="" id="myorgs">My Organizations</a> </li>
</ul>

<div id="meetingpad">
<div id="meetingsidebar">

<ul class="meetingsidebar" id="meetingsidebar_disp">
<li> <a href="#" id="min"> Meetings I'm In ({{meetingsin|length}}) </a> </li>
<li> <a href="#" id="mcr"> Meetings I Created ({{meetingscreated|length}}) </a> </li>
<li> <a href="#" id="mpa"> Past Meetings ({{meetingspast|length}}) </a> </li>
</ul>
<ul class="meetingsidebar" id="orgsidebar_disp">

</ul>

</div> <!-- end of meeting sidebar -->

<div id="meetings_in" style="height: 400px; overflow: scroll;">
<table class="inbox">
<tr class="headline">
<th></th>
<th> Starting </th>
<th> Ends </th>
<th> TimeZone </th>
</tr>
{% for meeting in meetingsin %}
<tr>
<td> <a href="../meeting/{{meeting.meeting_id}}"> {{meeting.title}}</a> </td>
<td> {% if meeting.uses_dt %}{{meeting.starttime}} {{meeting.startdate}} {% else %} n/a {% endif %} </td>
<td> {% if meeting.uses_dt %}{{meeting.endtime}} {{meeting.enddate}} {% else %} n/a {% endif %}</td>
<td> {{meeting.timezone}} </td>
</tr>
{% endfor %}
</table>
</div>

<div id="meetings_created" style="height: 400px; overflow: scroll;">
<table class="inbox">
<tr class="headline">
<th></th>
<th> Starting </th>
<th> Ends </th>
<th> TimeZone </th>
</tr>
{% for meeting in meetingscreated %}
<tr>
<td> <a href="../meeting/{{meeting.meeting_id}}"> {{meeting.title}}</a> </td>
<td> {% if meeting.uses_dt %}{{meeting.starttime}} {{meeting.startdate}} {% else %} n/a {% endif %} </td>
<td> {% if meeting.uses_dt %}{{meeting.endtime}} {{meeting.enddate}} {% else %} n/a {% endif %}</td>
<td> {{meeting.timezone}} </td>
</tr>
{% endfor %}
</table>
</div>

<div id="meetings_past" style="height: 400px; overflow: scroll;">
<table class="inbox">
<tr class="headline">
<th></th>
<th> Starting </th>
<th> Ends </th>
<th> TimeZone </th>
</tr>
{% for meeting in meetingspast %}
<tr>
<td> <a href="../meeting/{{meeting.meeting_id}}"> {{meeting.title}}</a> </td>
<td> {% if meeting.uses_dt %}{{meeting.starttime}} {{meeting.startdate}} {% else %} n/a {% endif %} </td>
<td> {% if meeting.uses_dt %}{{meeting.endtime}} {{meeting.enddate}} {% else %} n/a {% endif %}</td>
<td> {{meeting.timezone}} </td>
</tr>
{% endfor %}
</div>
</table>
</div> <!-- End of Meeting List -->

<div id="orglist" style="height: 400px; overflow: scroll;">
<table class="inbox">
<tr class="headline">
<th></th>
</tr>
<div id="meetings_in">
{% for org in organizations %}
<tr>
<td> <a href="../organization/{{org.page_id}}"> {{org.name}}</a> </td>
</tr>
{% endfor %}
</div>
</table>
</div>

</div> 

</body>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>

$(document).ready(function() {
	$('#orgsidebar_disp').hide();
	$('#orglist').hide();
	$('#meetings_past').hide();
	$('#meetings_created').hide();

	$('#mymeetings').click(function(e) {
		e.preventDefault();
		$('#orgsidebar_disp').hide();
		$('#orglist').hide();
		$('#meetingsidebar_disp').show();
		$('#meetings_in').show();
	});
	$('#myorgs').click(function(e) {
		e.preventDefault();
		$('#orgsidebar_disp').show();
		$('#orglist').show();

		$('#meetingsidebar_disp').hide();
		$('#meetings_in').hide();
		$('#meetings_created').hide();
		$('#meetings_past').hide();
	});

	$('#min').click(function(e) {
		e.preventDefault();
		$('#meetings_in').show();
		$('#meetings_created').hide();
		$('#meetings_past').hide();
	});
	$('#mcr').click(function(e) {
		e.preventDefault();
		$('#meetings_in').hide();
		$('#meetings_created').show();
		$('#meetings_past').hide();
	});
	$('#mpa').click(function(e) {
		e.preventDefault();
		$('#meetings_in').hide();
		$('#meetings_created').hide();
		$('#meetings_past').show();
	});
});

</script>
</html>

meetingapp/templates/setinterview.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<link href="{% static "formbase.css" %}" rel="stylesheet" type="text/css">

<div class="center_block container" style="min-width: 720px;">
	<div style="text-align: center;">
		<h2 style="text-align: center;">Set Interview</h2>
		<img src="{% static "flow2.jpg" %}">
	</div>
	<div class="form_block">
		<form class="form-horizontal" id="mform" style="margin-top: 25px;" method="post">
			{% csrf_token %}
			<input type="hidden" name="submit_request" value="submit_request">
			<div class="control-group">
				<label class="control-label">Invitee</label>
				<div class="controls">
					{{ form.email }}
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Who is this person or group?</label>
				<div class="controls">
					{{ form.desc }}
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Has he/she already agreed to come?</label>
				<div class="controls nobullet">
					{{ form.agreed}}
				</div>
			</div>
			{% if uses_dt %}
			<div class="control-group">
				<label class="control-label" for="inputDate">Question Period: Start Date</label>
				<div class="controls">
					<input type="text" name="startdate" id="id_startdate">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="inputTime">Start Time</label>
				<div class="controls">
					{{ form.starttime }}
				</div>
			</div>
			{% if time_mismatch %}
			<div class="control-group">
				<div class="controls">
					<h5 style="color: red;">Date/time error: the question period ends before it starts!</h5>
				</div>
			</div>
			{% endif %}
			<div class="control-group">
				<label class="control-label" for="inputDate">End Date</label>
				<div class="controls">
					<input type="text" name="enddate" id="id_enddate">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="inputTime">End Time</label>
				<div class="controls">
					{{ form.endtime }}
				</div>
			</div>
			{% endif %}
		</form>
	</div>
	<div class="blurb_block" style="font-size: 14px; margin-top: 25px; vertical-align: middle;">
		<h4 style="text-align: center;">Info</h4><br>
		<text>For the interview, you (the host) invite, by email, a person to be interviewed. This person can be yourself.</text><br><br>
		<text>If the invitee has already agreed to come, the interview will proceed as normal. While the question period is active, members will be able to ask you questions.</text><br><br>
		<text>If the invitee has not yet agreed to come, the interview will be in an inactive state until he visits the interview page (sent to him in an email), logs in, and either agrees or disagrees to be interview.</text>
		<text>When the meeting starts, you will be able to view these questions and send them out one-by-one for everyone to see. The invitee will then be able to answer the questions.</text><br><br>
	</div>
	<div class="footer_block">
		<button type="submit" id="sub" class="btn btn-primary">Set</button>
	</div>
</div>

<script>

$(document).ready(function() {

	$('#sub').click(function() {
		$('#mform').submit();
	});

	$(function() {
	    $( "#id_startdate" ).datepicker();
	    $( "#id_enddate").datepicker();
	});


    {% if form.errors or dterrors %}
        html = '<h4 style="text-align: center;">Errors</h4><br><text style="color: red;">';
        {% if form.email.errors %}
        html += 'Interviews are required to have an invitee.<br><br>';
        {% endif %}
        {% if form.agreed.errors %}
        html += 'Please specify whether the invitee has or has not agreed to come.<br><br>';
        {% endif %}
        {% if form.desc.errors %}
        html += 'Please supply a description of the invitee.<br><br>'
        {% endif %}
        {% if form.startdate.errors %}
        html += 'Start date required.<br><br>'
        {% endif %}
        {% if form.starttime.errors %}
        html += 'Start time required.<br><br>'
        {% endif %}
        {% if form.enddate.errors %}
        html += 'End date required.<br><br>'
        {% endif %}
        {% if form.endtime.errors %}
        html += 'End time required.<br><br>'
        {% endif %}
        $('.blurb_block').html(html);
    {% endif %}
});
</script>

{% endblock %}